"""M5 registry: artefacts, hashed keys, append-only audit, jobs.

Revision ID: 0001_m5
Revises:
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "0001_m5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    dialect = op.get_bind().dialect.name
    serial = "INTEGER PRIMARY KEY" if dialect == "sqlite" else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS schema_meta (
            key TEXT PRIMARY KEY,
            value TEXT
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS artefacts (
            job_id TEXT NOT NULL,
            kind TEXT NOT NULL,
            path TEXT NOT NULL,
            sha256 TEXT,
            dirty INTEGER DEFAULT 0,
            meta TEXT,
            PRIMARY KEY (job_id, kind, path)
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS api_keys (
            id {serial},
            role TEXT NOT NULL,
            access TEXT NOT NULL,
            key_hash TEXT NOT NULL
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS audit_events (
            id {serial},
            ts TEXT NOT NULL,
            role TEXT,
            action TEXT NOT NULL,
            resource TEXT,
            payload TEXT
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS jobs (
            id TEXT PRIMARY KEY,
            state TEXT NOT NULL,
            job_key TEXT,
            extra TEXT
        )
        """
    )
    op.execute(
        f"""
        CREATE TABLE IF NOT EXISTS job_events (
            id {serial},
            job_id TEXT NOT NULL,
            name TEXT NOT NULL,
            payload TEXT
        )
        """
    )
    op.execute(
        "INSERT OR REPLACE INTO schema_meta(key, value) VALUES ('schema_version', '2')"
        if op.get_bind().dialect.name == "sqlite"
        else "INSERT INTO schema_meta(key, value) VALUES ('schema_version', '2') "
        "ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value"
    )
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        op.execute(
            """
            CREATE TRIGGER IF NOT EXISTS audit_events_no_update
            BEFORE UPDATE ON audit_events
            BEGIN
                SELECT RAISE(ABORT, 'audit_events is append-only');
            END
            """
        )
        op.execute(
            """
            CREATE TRIGGER IF NOT EXISTS audit_events_no_delete
            BEFORE DELETE ON audit_events
            BEGIN
                SELECT RAISE(ABORT, 'audit_events is append-only');
            END
            """
        )
    else:
        op.execute(
            """
            CREATE OR REPLACE FUNCTION audit_events_append_only()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_events is append-only';
            END;
            $$ LANGUAGE plpgsql
            """
        )
        op.execute("DROP TRIGGER IF EXISTS audit_events_no_update ON audit_events")
        op.execute("DROP TRIGGER IF EXISTS audit_events_no_delete ON audit_events")
        op.execute(
            """
            CREATE TRIGGER audit_events_no_update
            BEFORE UPDATE ON audit_events
            FOR EACH ROW EXECUTE FUNCTION audit_events_append_only()
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_events_no_delete
            BEFORE DELETE ON audit_events
            FOR EACH ROW EXECUTE FUNCTION audit_events_append_only()
            """
        )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS job_events")
    op.execute("DROP TABLE IF EXISTS jobs")
    op.execute("DROP TABLE IF EXISTS audit_events")
    op.execute("DROP TABLE IF EXISTS api_keys")
    op.execute("DROP TABLE IF EXISTS artefacts")
    op.execute("DROP TABLE IF EXISTS schema_meta")
