#!/usr/bin/env python3
"""Generate docs/tools.md, docs/exports.md stamp, README REAL/STUB, ARCHITECTURE.md."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from threadforge.agent_tools import TOOL_REGISTRY  # noqa: E402
from threadforge.capabilities import CAPABILITIES, capability_table  # noqa: E402
from threadforge.cascade import CASCADE_KINDS_12  # noqa: E402


def write_tools_md() -> Path:
    rows = [
        "# ThreadForge agent tools",
        "",
        "AUTO-GENERATED by `scripts/gen_docs.py`. Do not hand-edit the table.",
        "",
        "| Tool | Purpose |",
        "|---|---|",
    ]
    for name, fn in sorted(TOOL_REGISTRY.items()):
        doc = (fn.__doc__ or name).strip().splitlines()[0]
        rows.append(f"| `{name}` | {doc} |")
    dest = ROOT / "docs" / "tools.md"
    dest.write_text("\n".join(rows) + "\n", encoding="utf-8")
    return dest


def stamp_exports_md() -> Path:
    dest = ROOT / "docs" / "exports.md"
    text = dest.read_text(encoding="utf-8")
    stamp = (
        "\n\n## Generated stamp\n\n"
        "AUTO-GENERATED stamp from `scripts/gen_docs.py`. Cascade kinds: "
        + ", ".join(k.value for k in CASCADE_KINDS_12)
        + ".\n"
    )
    marker = "\n\n## Generated stamp\n"
    if marker in text:
        text = text.split(marker, 1)[0]
    dest.write_text(text.rstrip() + stamp, encoding="utf-8")
    return dest


def write_architecture() -> Path:
    nodes = [
        ("ingest", 40, 40, "DEXPI ingest"),
        ("topo", 220, 40, "Topology"),
        ("route", 400, 40, "A* routes"),
        ("clash", 580, 40, "Clash"),
        ("pcf", 40, 140, "PCF"),
        ("iso", 220, 140, "Iso/GA"),
        ("awp", 400, 140, "AWP/4D"),
        ("http", 580, 140, "HTTP/MCP"),
    ]
    edges = [
        ("ingest", "topo"),
        ("topo", "route"),
        ("route", "clash"),
        ("route", "pcf"),
        ("route", "iso"),
        ("topo", "awp"),
        ("pcf", "http"),
        ("iso", "http"),
        ("awp", "http"),
    ]
    pos = {n: (x, y) for n, x, y, _ in nodes}
    svg = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="760" height="220" viewBox="0 0 760 220">',
        '<rect width="100%" height="100%" fill="#f8fafc"/>',
    ]
    for a, b in edges:
        x1, y1 = pos[a]
        x2, y2 = pos[b]
        svg.append(
            f'<line data-edge="{a}-{b}" x1="{x1 + 70}" y1="{y1 + 18}" x2="{x2}" y2="{y2 + 18}" '
            f'stroke="#64748b" stroke-width="1.5" marker-end="url(#arr)"/>'
        )
    svg.insert(
        2,
        '<defs><marker id="arr" markerWidth="8" markerHeight="8" refX="8" refY="4" orient="auto">'
        '<path d="M0,0 L8,4 L0,8 z" fill="#64748b"/></marker></defs>',
    )
    for nid, x, y, label in nodes:
        svg.append(
            f'<rect id="node-{nid}" x="{x}" y="{y}" width="140" height="36" rx="6" '
            f'fill="#1e293b" stroke="#38bdf8"/>'
        )
        svg.append(
            f'<text x="{x + 70}" y="{y + 23}" text-anchor="middle" fill="#f8fafc" '
            f'font-family="monospace" font-size="11">{label}</text>'
        )
    svg.append("</svg>")
    dest = ROOT / "ARCHITECTURE.md"
    dest.write_text(
        "# ThreadForge architecture\n\n"
        "AUTO-GENERATED DAG by `scripts/gen_docs.py`.\n\n"
        + "\n".join(svg)
        + "\n",
        encoding="utf-8",
    )
    return dest


def patch_readme() -> Path:
    dest = ROOT / "README.md"
    text = dest.read_text(encoding="utf-8")
    table = "## REAL vs STUB\n\n" + capability_table() + "\n"
    start = text.find("## REAL vs STUB")
    end = text.find("## Package layout")
    if start == -1 or end == -1:
        raise SystemExit("README markers missing")
    dest.write_text(text[:start] + table + "\n" + text[end:], encoding="utf-8")
    return dest


def main() -> int:
    write_tools_md()
    stamp_exports_md()
    write_architecture()
    patch_readme()
    print(
        f"tools={len(TOOL_REGISTRY)} capabilities={len(CAPABILITIES)} "
        f"kinds={len(CASCADE_KINDS_12)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
